/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.harvard;

import java.io.FileInputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.util.Properties;

import edu.harvard.Logic.Database;

public class App {
	public static void main(String[] args) {
		Properties prop = new Properties();
		ServerSocket serverSocket = null;
		try (FileInputStream input = new FileInputStream("../config.properties")) {
			prop.load(input);

			String port = prop.getProperty("port");

			serverSocket = new ServerSocket(Integer.parseInt(port));
			Database db = new Database();

			while (true) {
				new AppThread(serverSocket.accept(), db).start();
			}
		} catch (IOException ex) {
			System.err.println("Unhandled I/O failure!");
			System.err.println(ex.getMessage());
			for (StackTraceElement ste : ex.getStackTrace()) {
				System.err.println(ste + "\n");
			}
		}
	}
}
